[package]
name = "node-agent"
version = "0.2.0"
edition = "2021"

[dependencies]
camelot-crypto = { path = "../../crates/camelot-crypto" }
camelot-lease = { path = "../../crates/camelot-lease" }
camelot-vfs = { path = "../../crates/camelot-vfs" }
axum = "0.7"
tokio = { version = "1.36", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1.7", features = ["v4", "serde"] }
wasmtime = "18.0.0"
base64 = "0.22"
sha2 = "0.10"
chrono = { version = "0.4.34", features = ["serde"] }
subtle = "2.6"
