import React, { useState, useEffect, useRef } from 'react';
import { 
  Shield, 
  ShieldCheck, 
  Terminal, 
  Layers, 
  Server, 
  Cpu, 
  Lock, 
  FileCode, 
  Database, 
  CheckCircle2, 
  XCircle, 
  AlertTriangle, 
  RefreshCw, 
  Play, 
  Search, 
  Eye, 
  ExternalLink, 
  Sparkles, 
  Activity, 
  ChevronRight, 
  Radio, 
  ArrowRight,
  Send,
  Zap,
  Boxes,
  HelpCircle,
  Clock,
  Fingerprint
} from 'lucide-react';
import confetti from 'canvas-confetti';

export interface ContractSchema {
  id: string;
  name: string;
  path: string;
  authority: 'Rust Privileged' | 'Go Edge Gateway' | 'Shared Contract';
  epoch: number;
  description: string;
  sampleJson: string;
}

export interface EffectManifestItem {
  id: string;
  taskId: string;
  correlationId: string;
  tenantId: string;
  workspaceId: string;
  authorityEpoch: number;
  kind: 'VFS_WRITE' | 'DEVICE_ACTION' | 'DATABASE_MIGRATE' | 'EXTERNAL_DISPATCH' | 'NETWORK_CALL';
  target: string;
  riskTier: 'R1' | 'R2' | 'R3' | 'R4' | 'R5' | 'R6';
  status: 'pending_approval' | 'approved' | 'denied' | 'verified_receipt';
  requiredEvidence: string[];
  manifestHash: string;
  rollbackRef: string;
  createdAt: string;
  leaseExpiry: string;
  decisionReason?: string;
}

export interface WebGpuNode {
  id: string;
  label: string;
  kind: 'mission' | 'task' | 'manifest' | 'lease' | 'receipt' | 'fact' | 'entity' | 'evidence';
  state: 'verified' | 'running' | 'approval_required' | 'failed' | 'quarantined';
  riskTier: string;
  trustTier: number;
  x: number;
  y: number;
  color: string;
}

export interface WebGpuEdge {
  id: string;
  source: string;
  target: string;
  kind: 'produced' | 'authorized_by' | 'verified_by' | 'emitted' | 'asserts';
  integrity: 'verified' | 'tampered';
}

const CONTRACT_SCHEMAS: ContractSchema[] = [
  {
    id: 'effect-manifest',
    name: 'effect-manifest.schema.json',
    path: 'contracts/schemas/effect-manifest.schema.json',
    authority: 'Rust Privileged',
    epoch: 104,
    description: 'Immutable specification of requested system mutation. Generated by task, sealed prior to policy decision.',
    sampleJson: JSON.stringify({
      "$schema": "https://camelot.invisionedmarketing.com/schemas/effect-manifest.v1.json",
      "schema_version": "1.0.0",
      "manifest_id": "man_01994a82-e67b-7b02-8c11-92b0c1284a91",
      "task_id": "tsk_01994a80-1a22-7994-b26a-8b89e9008f1b",
      "correlation_id": "cor_9981240182",
      "tenant_id": "ten_01",
      "workspace_id": "ws_01",
      "authority_epoch": 104,
      "kind": "VFS_WRITE",
      "target": "vfs:///opt/camelot/crm/integrations.yaml",
      "immutable_inputs": {
        "content_hash": "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "byte_length": 4120
      },
      "required_evidence": ["z3://proofs/p44_sat", "test://e2e/crm_auth"],
      "constraints": {
        "max_duration_ms": 5000,
        "enforce_sandbox": true
      }
    }, null, 2)
  },
  {
    id: 'capability-lease',
    name: 'capability-lease.schema.json',
    path: 'contracts/schemas/capability-lease.schema.json',
    authority: 'Rust Privileged',
    epoch: 104,
    description: 'Ed25519-signed authorization granting ephemeral privilege to execute an approved manifest. Never issued by Bifrost.',
    sampleJson: JSON.stringify({
      "$schema": "https://camelot.invisionedmarketing.com/schemas/capability-lease.v1.json",
      "lease_id": "lease_01994a83-500b-71ef-89a1-77bfa21298d0",
      "authority_epoch": 104,
      "manifest_hash": "sha256:d4829fa014b22c7a91602931a7b8e100f937402a11b84920b784a918e907d912",
      "tenant_id": "ten_01",
      "task_id": "tsk_01994a80-1a22-7994-b26a-8b89e9008f1b",
      "subject": { "agent_id": "sir_codex", "node_id": "vps-cybertronia-01" },
      "permissions": ["VFS_WRITE:SCOPED", "CGROUP_LIMIT:7.2GB"],
      "limits": { "max_cpu_percent": 80, "max_memory_mb": 512, "timeout_ms": 3000 },
      "issued_at": "2026-09-07T08:14:00Z",
      "expires_at": "2026-09-07T08:19:00Z",
      "revocable": true,
      "signature": "ed25519:6c2a8b9f01e23...3f99401"
    }, null, 2)
  },
  {
    id: 'receipt',
    name: 'receipt.schema.json',
    path: 'contracts/schemas/receipt.schema.json',
    authority: 'Rust Privileged',
    epoch: 104,
    description: 'Monotonic cryptographic receipt recorded in SQLite WAL2 hash-chain. Verifies completed execution.',
    sampleJson: JSON.stringify({
      "$schema": "https://camelot.invisionedmarketing.com/schemas/receipt.v1.json",
      "receipt_id": "rec_01994a85-bc32-7201-9a76-0045e8b091f2",
      "previous_receipt_hash": "sha256:8f74a9b24cd61e3892ab4f012c8e3902",
      "block_height": 851,
      "tenant_id": "ten_01",
      "task_id": "tsk_01994a80-1a22-7994-b26a-8b89e9008f1b",
      "manifest_id": "man_01994a82-e67b-7b02-8c11-92b0c1284a91",
      "lease_id": "lease_01994a83-500b-71ef-89a1-77bfa21298d0",
      "execution_duration_ms": 14.8,
      "wal2_sealed": true,
      "r5_r6_seal": true,
      "gideon_sat": true,
      "timestamp": "2026-09-07T08:14:15Z"
    }, null, 2)
  },
  {
    id: 'context-packet',
    name: 'context-packet.schema.json',
    path: 'contracts/schemas/context-packet.schema.json',
    authority: 'Shared Contract',
    epoch: 104,
    description: 'Tenant-scoped temporal context packet rehydrated from Neo4j & Qdrant with provenance receipts.',
    sampleJson: JSON.stringify({
      "context_packet_id": "ctx_01994a81-77ca-7681-9b12-5881a970e4b2",
      "task_id": "tsk_01994a80-1a22-7994-b26a-8b89e9008f1b",
      "tenant_id": "ten_01",
      "workspace_id": "ws_01",
      "facts": [
        {
          "fact_id": "fct_9021",
          "predicate": "REQUIRES_HUMAN_APPROVAL",
          "confidence": 0.99,
          "valid_from": "2026-09-07T00:00:00Z",
          "recorded_from": "2026-09-07T08:00:00Z",
          "source_hash": "sha256:77bc09..."
        }
      ],
      "evidence_refs": ["receipt://rec_01994a80"],
      "token_count": 1420,
      "retrieval_receipt_ref": "receipt://rec_retrieval_850",
      "expires_at": "2026-09-07T08:30:00Z"
    }, null, 2)
  }
];

const INITIAL_APPROVALS: EffectManifestItem[] = [
  {
    id: 'appr-01',
    taskId: 'tsk_01994a80-1a22',
    correlationId: 'cor_9981240182',
    tenantId: 'ten_01',
    workspaceId: 'ws_01',
    authorityEpoch: 104,
    kind: 'VFS_WRITE',
    target: '/opt/camelot/crm/production_sync.yaml',
    riskTier: 'R4',
    status: 'pending_approval',
    requiredEvidence: [
      'gideon://z3/proofs/p44_sat (Theorem Proved)',
      'test://e2e/crm_handshake (Pass 12/12)',
      'sentinel://policy/tenant_isolation (Enforced)'
    ],
    manifestHash: 'sha256:9f4e21a084bc671e...8821',
    rollbackRef: 'rollback://vfs/snapshot_rev411',
    createdAt: '12:08:40',
    leaseExpiry: '5m 00s'
  },
  {
    id: 'appr-02',
    taskId: 'tsk_01994a91-44bb',
    correlationId: 'cor_9981240210',
    tenantId: 'ten_01',
    workspaceId: 'ws_01',
    authorityEpoch: 104,
    kind: 'DATABASE_MIGRATE',
    target: 'neo4j://cybertronia/constraints/temporal_facts_idx',
    riskTier: 'R5',
    status: 'pending_approval',
    requiredEvidence: [
      'gideon://z3/schema_conformance (SAT)',
      'backup://wal2/checkpoint_850 (Verified)'
    ],
    manifestHash: 'sha256:3a4b91f09c2e...24c6',
    rollbackRef: 'rollback://neo4j/cypher_revert_idx.cyp',
    createdAt: '12:10:15',
    leaseExpiry: '10m 00s'
  },
  {
    id: 'appr-03',
    taskId: 'tsk_01994a77-90ff',
    correlationId: 'cor_9981240099',
    tenantId: 'ten_01',
    workspaceId: 'ws_01',
    authorityEpoch: 104,
    kind: 'NETWORK_CALL',
    target: 'tailscale://100.112.44.18:8443 (Edge Node Alpha)',
    riskTier: 'R3',
    status: 'verified_receipt',
    requiredEvidence: [
      'sentinel://lease/token_valid (Granted)',
      'ed25519://node_agent/signed_identity (Valid)'
    ],
    manifestHash: 'sha256:e3b0c44298fc...b855',
    rollbackRef: 'rollback://network/revoke_lease_token',
    createdAt: '12:02:11',
    leaseExpiry: 'EXPIRED (Executed)',
    decisionReason: 'Sovereign approved via Excalibur Gate'
  }
];

const INITIAL_NODES: WebGpuNode[] = [
  { id: 'mission_01', label: 'CRM Integration', kind: 'mission', state: 'approval_required', riskTier: 'R4', trustTier: 1, x: 200, y: 130, color: '#f59e0b' },
  { id: 'task_01', label: 'VFS Config Patch', kind: 'task', state: 'running', riskTier: 'R4', trustTier: 1, x: 380, y: 110, color: '#22d3ee' },
  { id: 'manifest_01', label: 'Manifest: 9f4e21a', kind: 'manifest', state: 'approval_required', riskTier: 'R4', trustTier: 0, x: 560, y: 120, color: '#f59e0b' },
  { id: 'lease_01', label: 'Lease: Sentinel 0x89f2', kind: 'lease', state: 'approval_required', riskTier: 'R4', trustTier: 2, x: 740, y: 90, color: '#c084fc' },
  { id: 'gideon_01', label: 'Gideon Z3 Invariant 44', kind: 'evidence', state: 'verified', riskTier: 'R1', trustTier: 3, x: 560, y: 240, color: '#10b981' },
  { id: 'receipt_01', label: 'Receipt #850 WAL2', kind: 'receipt', state: 'verified', riskTier: 'R1', trustTier: 3, x: 740, y: 220, color: '#d4af37' },
  { id: 'neo4j_fact', label: 'Fact: TenantIsol', kind: 'fact', state: 'verified', riskTier: 'R1', trustTier: 2, x: 380, y: 260, color: '#d4af37' },
  { id: 'qdrant_emb', label: 'Qdrant: 24-dim Vector', kind: 'entity', state: 'verified', riskTier: 'R1', trustTier: 2, x: 200, y: 260, color: '#94a3b8' }
];

const INITIAL_EDGES: WebGpuEdge[] = [
  { id: 'e1', source: 'mission_01', target: 'task_01', kind: 'produced', integrity: 'verified' },
  { id: 'e2', source: 'task_01', target: 'manifest_01', kind: 'produced', integrity: 'verified' },
  { id: 'e3', source: 'manifest_01', target: 'lease_01', kind: 'authorized_by', integrity: 'verified' },
  { id: 'e4', source: 'task_01', target: 'gideon_01', kind: 'verified_by', integrity: 'verified' },
  { id: 'e5', source: 'lease_01', target: 'receipt_01', kind: 'emitted', integrity: 'verified' },
  { id: 'e6', source: 'task_01', target: 'neo4j_fact', kind: 'asserts', integrity: 'verified' },
  { id: 'e7', source: 'neo4j_fact', target: 'qdrant_emb', kind: 'asserts', integrity: 'verified' }
];

export const OperatorConsoleHtmx: React.FC<{
  onExecuteCommand?: (cmd: string) => void;
  onNavigateTab?: (tab: string) => void;
}> = ({ onExecuteCommand, onNavigateTab }) => {
  const [activeTab, setActiveTab] = useState<'approvals' | 'contracts' | 'webgpu' | 'architecture' | 'adversarial'>('approvals');
  const [approvals, setApprovals] = useState<EffectManifestItem[]>(INITIAL_APPROVALS);
  const [selectedApproval, setSelectedApproval] = useState<EffectManifestItem | null>(INITIAL_APPROVALS[0]);
  const [selectedSchema, setSelectedSchema] = useState<ContractSchema>(CONTRACT_SCHEMAS[0]);
  const [selectedNode, setSelectedNode] = useState<WebGpuNode | null>(INITIAL_NODES[0]);
  const [sseActive, setSseActive] = useState<boolean>(true);
  const [lastSseEvent, setLastSseEvent] = useState<string>('receipt.issued: rec_01994a80 (WAL2 block #850)');
  const [adversarialLogs, setAdversarialLogs] = useState<string[]>([
    '[INIT]: Adversarial suite ready. 8 security boundary checks active.'
  ]);

  // WebGPU Simulation State
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const [webGpuStatus, setWebGpuStatus] = useState<'simulated_webgpu' | 'dom_fallback'>('simulated_webgpu');
  const [animationTick, setAnimationTick] = useState(0);

  // SSE Event simulation
  useEffect(() => {
    if (!sseActive) return;
    const interval = setInterval(() => {
      const events = [
        'vitals.updated: usedRamMB: 4890MB / 8192MB • cgroup: 7.2GB cap',
        'graph.patch: node_01994a82 state=verified epoch=104',
        'receipt.issued: rec_01994a85 (WAL2 checkpoint block #851)',
        'sentinel.lease: audit pass (0 revoked leases)'
      ];
      const picked = events[Math.floor(Math.random() * events.length)];
      setLastSseEvent(`${picked} [${new Date().toLocaleTimeString()}]`);
    }, 4500);
    return () => clearInterval(interval);
  }, [sseActive]);

  // WebGPU Canvas renderer (Canvas2D progressive fallback mimicking the WGSL node shader)
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    let animId: number;

    const render = () => {
      ctx.clearRect(0, 0, canvas.width, canvas.height);

      // Background grid
      ctx.strokeStyle = 'rgba(212, 175, 55, 0.06)';
      ctx.lineWidth = 1;
      const step = 32;
      for (let x = 0; x < canvas.width; x += step) {
        ctx.beginPath();
        ctx.moveTo(x, 0);
        ctx.lineTo(x, canvas.height);
        ctx.stroke();
      }
      for (let y = 0; y < canvas.height; y += step) {
        ctx.beginPath();
        ctx.moveTo(0, y);
        ctx.lineTo(canvas.width, y);
        ctx.stroke();
      }

      // Edges Pass
      INITIAL_EDGES.forEach((edge) => {
        const s = INITIAL_NODES.find(n => n.id === edge.source);
        const t = INITIAL_NODES.find(n => n.id === edge.target);
        if (!s || !t) return;

        ctx.strokeStyle = edge.integrity === 'verified' ? 'rgba(212, 175, 55, 0.4)' : 'rgba(239, 68, 68, 0.7)';
        ctx.lineWidth = 2;
        ctx.setLineDash(edge.kind === 'produced' ? [4, 2] : []);
        ctx.beginPath();
        ctx.moveTo(s.x, s.y);
        ctx.lineTo(t.x, t.y);
        ctx.stroke();
        ctx.setLineDash([]);
      });

      // Nodes Pass with WGSL Halo Simulation
      const t = Date.now() * 0.003;
      INITIAL_NODES.forEach((node) => {
        const isSelected = selectedNode?.id === node.id;
        
        // Halo pass for active states
        if (node.state === 'approval_required' || node.state === 'running') {
          const haloRadius = 24 + Math.sin(t + node.x) * 6;
          const grad = ctx.createRadialGradient(node.x, node.y, 10, node.x, node.y, haloRadius);
          grad.addColorStop(0, node.color + '44');
          grad.addColorStop(1, 'transparent');
          ctx.fillStyle = grad;
          ctx.beginPath();
          ctx.arc(node.x, node.y, haloRadius, 0, Math.PI * 2);
          ctx.fill();
        }

        // Core Node
        ctx.fillStyle = node.color;
        ctx.beginPath();
        ctx.arc(node.x, node.y, isSelected ? 16 : 12, 0, Math.PI * 2);
        ctx.fill();

        // Node outline
        ctx.strokeStyle = isSelected ? '#ffffff' : '#050505';
        ctx.lineWidth = 2.5;
        ctx.stroke();

        // Node Label
        ctx.fillStyle = '#f1f5f9';
        ctx.font = '10px JetBrains Mono, monospace';
        ctx.fillText(node.label, node.x - 30, node.y + 26);
      });

      animId = requestAnimationFrame(render);
    };

    render();
    return () => cancelAnimationFrame(animId);
  }, [selectedNode]);

  // Handle Approve
  const handleApprove = (item: EffectManifestItem) => {
    confetti({ particleCount: 40, spread: 60, origin: { y: 0.7 } });
    setApprovals(prev => prev.map(a => a.id === item.id ? { ...a, status: 'approved', decisionReason: 'Approved by Sovereign Operator via HTMX POST' } : a));
    if (selectedApproval?.id === item.id) {
      setSelectedApproval({ ...item, status: 'approved', decisionReason: 'Approved by Sovereign Operator via HTMX POST' });
    }
    if (onExecuteCommand) {
      onExecuteCommand(`camelot-lease --issue --manifest-id ${item.id} --epoch 104`);
    }
  };

  // Handle Deny
  const handleDeny = (item: EffectManifestItem) => {
    setApprovals(prev => prev.map(a => a.id === item.id ? { ...a, status: 'denied', decisionReason: 'Rejected by Sovereign Operator (Fails closed)' } : a));
    if (selectedApproval?.id === item.id) {
      setSelectedApproval({ ...item, status: 'denied', decisionReason: 'Rejected by Sovereign Operator (Fails closed)' });
    }
    if (onExecuteCommand) {
      onExecuteCommand(`camelot-policy --reject --manifest-id ${item.id} --reason "Operator veto"`);
    }
  };

  // Run Adversarial Test
  const runAdversarialTest = (testName: string, expectedOutcome: string) => {
    const timestamp = new Date().toLocaleTimeString();
    setAdversarialLogs(prev => [
      `[${timestamp}] 🧪 TEST RUN: "${testName}"...`,
      ...prev
    ]);

    setTimeout(() => {
      setAdversarialLogs(prev => [
        `[${timestamp}] 🛡️ RESULT: BLOCKED / FAILS CLOSED -> ${expectedOutcome}`,
        ...prev
      ]);
    }, 450);
  };

  return (
    <div className="w-full min-h-[calc(100vh-80px)] bg-[#050505] space-y-3 font-mono text-slate-200 p-2 sm:p-4">
      
      {/* Top Architecture Assertion Ribbon */}
      <div className="p-3 sm:p-4 rounded-xl bg-[#070b14] border border-[#D4AF37]/50 shadow-2xl backdrop-blur-xl flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-[#D4AF37] animate-pulse" />
            <h2 className="text-sm sm:text-base font-bold text-[#D4AF37] tracking-wider uppercase flex items-center gap-2">
              <span>OPERATOR CONSOLE & AUTHORITY BOUNDARIES</span>
              <span className="text-slate-600 text-xs">•</span>
              <span className="text-cyan-300 font-sans text-xs">GO CONTROL PLANE ⊕ RUST PRIVILEGE</span>
            </h2>
          </div>
          <p className="text-xs text-slate-400 mt-1">
            Strict Planner/Executor/Verifier separation: Bifrost routes & terminates mTLS; Sentinel solely issues leases; Gideon proves invariants via Z3; WebGPU renders graph topology as progressive enhancement over HTMX evidence fragments.
          </p>
        </div>

        {/* Live SSE Stream Badge & VPS Hub link */}
        <div className="flex items-center gap-2">
          {onNavigateTab && (
            <button
              onClick={() => onNavigateTab('vps_init')}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-[#2E0854] hover:bg-purple-900 border border-[#D4AF37]/60 text-[#D4AF37] text-xs font-bold transition-all shadow-[0_0_12px_rgba(212,175,55,0.25)] cursor-pointer shrink-0"
              title="Open VPS Hub Initiation Plan for vps3573819"
            >
              <Server className="w-3.5 h-3.5 text-[#D4AF37]" />
              <span>VPS HUB INITIATION</span>
            </button>
          )}

          <div className="flex items-center gap-3 bg-black/80 px-3 py-2 rounded-xl border border-cyan-800/60 text-xs shrink-0">
            <Radio className={`w-3.5 h-3.5 ${sseActive ? 'text-emerald-400 animate-pulse' : 'text-slate-600'}`} />
            <div className="space-y-0.5">
              <div className="flex items-center gap-1.5">
                <span className="text-[10px] text-slate-400 font-bold uppercase">SSE BUS:</span>
                <span className="text-emerald-400 font-bold text-[10px]">CONNECTED</span>
              </div>
              <div className="text-[10px] text-cyan-300 max-w-[140px] sm:max-w-xs truncate">
                {lastSseEvent}
              </div>
            </div>
            <button
              onClick={() => setSseActive(!sseActive)}
              className="text-[9px] px-1.5 py-0.5 rounded bg-slate-800 text-slate-300 hover:text-white cursor-pointer"
            >
              {sseActive ? 'PAUSE' : 'RESUME'}
            </button>
          </div>
        </div>
      </div>

      {/* Sub-Navigation Tabs */}
      <div className="flex items-center gap-2 border-b border-cyan-900/60 pb-2 overflow-x-auto">
        <button
          onClick={() => setActiveTab('approvals')}
          className={`px-3 py-1.5 rounded-xl text-xs font-bold flex items-center gap-2 transition-all cursor-pointer ${
            activeTab === 'approvals'
              ? 'bg-[#2E0854] text-[#D4AF37] border border-[#D4AF37]/60 shadow-[0_0_15px_rgba(212,175,55,0.3)]'
              : 'text-slate-400 hover:text-slate-200 bg-slate-900/60'
          }`}
        >
          <Lock className="w-3.5 h-3.5" />
          <span>APPROVAL DRAWER & MANIFESTS ({approvals.filter(a => a.status === 'pending_approval').length})</span>
        </button>

        <button
          onClick={() => setActiveTab('webgpu')}
          className={`px-3 py-1.5 rounded-xl text-xs font-bold flex items-center gap-2 transition-all cursor-pointer ${
            activeTab === 'webgpu'
              ? 'bg-[#2E0854] text-[#D4AF37] border border-[#D4AF37]/60 shadow-[0_0_15px_rgba(212,175,55,0.3)]'
              : 'text-slate-400 hover:text-slate-200 bg-slate-900/60'
          }`}
        >
          <Activity className="w-3.5 h-3.5" />
          <span>WEBGPU GRAPH HUD & WGSL PIPELINE</span>
        </button>

        <button
          onClick={() => setActiveTab('contracts')}
          className={`px-3 py-1.5 rounded-xl text-xs font-bold flex items-center gap-2 transition-all cursor-pointer ${
            activeTab === 'contracts'
              ? 'bg-[#2E0854] text-[#D4AF37] border border-[#D4AF37]/60 shadow-[0_0_15px_rgba(212,175,55,0.3)]'
              : 'text-slate-400 hover:text-slate-200 bg-slate-900/60'
          }`}
        >
          <FileCode className="w-3.5 h-3.5" />
          <span>VERSIONED CONTRACTS ({CONTRACT_SCHEMAS.length})</span>
        </button>

        <button
          onClick={() => setActiveTab('architecture')}
          className={`px-3 py-1.5 rounded-xl text-xs font-bold flex items-center gap-2 transition-all cursor-pointer ${
            activeTab === 'architecture'
              ? 'bg-[#2E0854] text-[#D4AF37] border border-[#D4AF37]/60 shadow-[0_0_15px_rgba(212,175,55,0.3)]'
              : 'text-slate-400 hover:text-slate-200 bg-slate-900/60'
          }`}
        >
          <Layers className="w-3.5 h-3.5" />
          <span>GO / RUST AUTHORITY MATRIX</span>
        </button>

        <button
          onClick={() => setActiveTab('adversarial')}
          className={`px-3 py-1.5 rounded-xl text-xs font-bold flex items-center gap-2 transition-all cursor-pointer ${
            activeTab === 'adversarial'
              ? 'bg-[#2E0854] text-[#D4AF37] border border-[#D4AF37]/60 shadow-[0_0_15px_rgba(212,175,55,0.3)]'
              : 'text-slate-400 hover:text-slate-200 bg-slate-900/60'
          }`}
        >
          <ShieldCheck className="w-3.5 h-3.5" />
          <span>ADVERSARIAL GAUNTLET (8 SUITES)</span>
        </button>
      </div>

      {/* ================= TAB 1: APPROVAL DRAWER & IMMUTABLE MANIFESTS ================= */}
      {activeTab === 'approvals' && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
          
          {/* Left: Manifest / Approval List */}
          <div className="lg:col-span-1 space-y-3">
            <div className="text-xs font-bold text-slate-400 uppercase tracking-wider flex items-center justify-between">
              <span>PENDING EFFECT MANIFESTS</span>
              <span className="text-[#D4AF37]">{approvals.length} TOTAL</span>
            </div>

            <div className="space-y-2.5">
              {approvals.map((item) => {
                const isSelected = selectedApproval?.id === item.id;
                return (
                  <div
                    key={item.id}
                    onClick={() => setSelectedApproval(item)}
                    className={`p-3 rounded-xl border transition-all cursor-pointer ${
                      isSelected
                        ? 'bg-[#120826] border-[#D4AF37] shadow-[0_0_15px_rgba(212,175,55,0.25)]'
                        : 'bg-[#090d18] border-slate-800 hover:border-cyan-800'
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span className={`px-2 py-0.5 rounded text-[10px] font-extrabold ${
                        item.riskTier === 'R5' ? 'bg-red-950 text-red-300 border border-red-500/40' :
                        item.riskTier === 'R4' ? 'bg-amber-950 text-amber-300 border border-amber-500/40' :
                        'bg-cyan-950 text-cyan-300 border border-cyan-500/40'
                      }`}>
                        {item.riskTier} • {item.kind}
                      </span>
                      <span className={`text-[10px] font-bold ${
                        item.status === 'pending_approval' ? 'text-amber-400 animate-pulse' :
                        item.status === 'approved' ? 'text-emerald-400' :
                        item.status === 'verified_receipt' ? 'text-[#D4AF37]' :
                        'text-red-400'
                      }`}>
                        {item.status.toUpperCase()}
                      </span>
                    </div>

                    <div className="text-xs font-bold text-white mt-1.5 truncate">
                      {item.target}
                    </div>

                    <div className="flex items-center justify-between text-[10px] text-slate-500 mt-2 font-mono">
                      <span>Task: {item.taskId}</span>
                      <span>Expires: {item.leaseExpiry}</span>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Right: Detailed Manifest Inspector & HTMX Action Form */}
          <div className="lg:col-span-2 space-y-4">
            {selectedApproval ? (
              <div className="p-5 rounded-2xl bg-[#090d18] border border-[#D4AF37]/40 shadow-2xl space-y-4">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-800 pb-3">
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="text-[10px] px-2 py-0.5 rounded bg-purple-950 text-purple-300 border border-purple-500/40 font-bold">
                        AUTHORITY EPOCH: {selectedApproval.authorityEpoch}
                      </span>
                      <span className="text-xs text-slate-500 font-mono">ID: {selectedApproval.id}</span>
                    </div>
                    <h3 className="text-sm sm:text-base font-bold text-white mt-1">
                      {selectedApproval.kind} ➔ {selectedApproval.target}
                    </h3>
                  </div>

                  <span className={`px-2.5 py-1 rounded-xl text-xs font-bold self-start sm:self-auto ${
                    selectedApproval.status === 'pending_approval' ? 'bg-amber-950 text-amber-300 border border-amber-500' :
                    selectedApproval.status === 'approved' ? 'bg-emerald-950 text-emerald-300 border border-emerald-500' :
                    'bg-slate-800 text-slate-300'
                  }`}>
                    STATUS: {selectedApproval.status.toUpperCase()}
                  </span>
                </div>

                {/* Grid of Verified Evidence */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
                  <div className="p-3 rounded-xl bg-black/60 border border-slate-800 space-y-1">
                    <span className="text-[10px] text-slate-500 uppercase block font-bold">Scope Context (Server-Derived)</span>
                    <div className="text-cyan-300 font-mono">tenant_id: {selectedApproval.tenantId}</div>
                    <div className="text-slate-400 font-mono">workspace_id: {selectedApproval.workspaceId}</div>
                    <div className="text-slate-500 font-mono text-[10px]">correlation: {selectedApproval.correlationId}</div>
                  </div>

                  <div className="p-3 rounded-xl bg-black/60 border border-slate-800 space-y-1">
                    <span className="text-[10px] text-slate-500 uppercase block font-bold">Cryptographic Seals</span>
                    <div className="text-[#D4AF37] font-mono text-[11px] truncate">
                      hash: {selectedApproval.manifestHash}
                    </div>
                    <div className="text-slate-400 font-mono text-[10px]">
                      rollback: {selectedApproval.rollbackRef}
                    </div>
                  </div>
                </div>

                {/* Evidence Links */}
                <div className="space-y-1.5">
                  <span className="text-[10px] text-slate-400 uppercase font-bold tracking-wider">
                    Required Formal Evidence (Gideon / Z3 / Sentinel)
                  </span>
                  <div className="space-y-1">
                    {selectedApproval.requiredEvidence.map((ev, idx) => (
                      <div key={idx} className="flex items-center gap-2 text-xs p-2 rounded bg-slate-900/80 border border-slate-800">
                        <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                        <span className="text-slate-300 font-mono">{ev}</span>
                      </div>
                    ))}
                  </div>
                </div>

                {/* HTMX Style Exact Effect Decision Forms */}
                {selectedApproval.status === 'pending_approval' ? (
                  <div className="pt-2 border-t border-slate-800 space-y-2">
                    <div className="text-[11px] text-slate-400 bg-black/50 p-2.5 rounded-xl border border-slate-800 flex items-center gap-2">
                      <Shield className="w-4 h-4 text-[#D4AF37] shrink-0" />
                      <span>
                        Sovereign Law: Browser submits only the exact decision, manifest ID, and session proof. Client cannot forge permissions, scopes, or lease limits.
                      </span>
                    </div>

                    <div className="flex items-center gap-3">
                      <button
                        onClick={() => handleApprove(selectedApproval)}
                        className="flex-1 py-2.5 rounded-xl bg-gradient-to-r from-[#D4AF37] to-amber-500 text-black font-extrabold text-xs flex items-center justify-center gap-2 shadow-[0_0_20px_rgba(212,175,55,0.4)] hover:brightness-110 active:scale-98 transition-all cursor-pointer"
                      >
                        <CheckCircle2 className="w-4 h-4" />
                        <span>APPROVE EXACT MANIFEST (POST /v1/effects/:id/decision)</span>
                      </button>

                      <button
                        onClick={() => handleDeny(selectedApproval)}
                        className="px-5 py-2.5 rounded-xl bg-red-950/80 hover:bg-red-900 border border-red-500/60 text-red-200 font-bold text-xs flex items-center gap-1.5 active:scale-98 transition-all cursor-pointer"
                      >
                        <XCircle className="w-4 h-4" />
                        <span>DENY & FAIL CLOSED</span>
                      </button>
                    </div>
                  </div>
                ) : (
                  <div className="p-3 rounded-xl bg-black/70 border border-slate-800 text-xs text-slate-300 flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                    <span>Decision Recorded: {selectedApproval.decisionReason || 'Immutable ledger receipt generated.'}</span>
                  </div>
                )}
              </div>
            ) : (
              <div className="p-12 text-center text-slate-500">
                Select an effect manifest to inspect provenance and evidence.
              </div>
            )}
          </div>
        </div>
      )}

      {/* ================= TAB 2: WEBGPU TOPOLOGY & SHADER PIPELINE ================= */}
      {activeTab === 'webgpu' && (
        <div className="space-y-4">
          <div className="p-4 rounded-2xl bg-[#090d18] border border-[#D4AF37]/30 flex flex-col md:flex-row md:items-center md:justify-between gap-3 text-xs">
            <div>
              <div className="flex items-center gap-2">
                <Activity className="w-4 h-4 text-cyan-400" />
                <h3 className="font-bold text-white text-sm">WEBGPU TOPOLOGY ENGINE (PROGRESSIVE ENHANCEMENT)</h3>
              </div>
              <p className="text-slate-400 mt-0.5">
                World Tree graph visualization using WGSL instanced billboards & edge passes. Accessible HTMX table mirror rendered underneath.
              </p>
            </div>

            <div className="flex items-center gap-2">
              <span className="px-2.5 py-1 rounded-lg bg-black border border-cyan-500/50 text-cyan-300 font-mono text-[10px]">
                SHADERS: nodes.wgsl + edges.wgsl
              </span>
              <span className="px-2.5 py-1 rounded-lg bg-emerald-950 border border-emerald-500/50 text-emerald-300 font-mono text-[10px]">
                PASS: 60 FPS • 0 MEMORY LEAK
              </span>
            </div>
          </div>

          {/* Interactive Canvas Viewport */}
          <div className="relative w-full h-80 rounded-2xl bg-[#050505] border-2 border-cyan-900/60 overflow-hidden shadow-2xl">
            <canvas
              ref={canvasRef}
              width={900}
              height={320}
              className="w-full h-full object-cover cursor-crosshair"
              onClick={(e) => {
                const rect = e.currentTarget.getBoundingClientRect();
                const clickX = ((e.clientX - rect.left) / rect.width) * 900;
                const clickY = ((e.clientY - rect.top) / rect.height) * 320;
                const found = INITIAL_NODES.find(n => Math.hypot(n.x - clickX, n.y - clickY) < 25);
                if (found) setSelectedNode(found);
              }}
            />

            {/* Floating Node Badge Overlay */}
            {selectedNode && (
              <div className="absolute top-3 left-3 p-3 rounded-xl bg-black/90 border border-[#D4AF37] text-xs space-y-1 shadow-2xl backdrop-blur-xl">
                <div className="flex items-center gap-2">
                  <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: selectedNode.color }} />
                  <span className="font-bold text-white">{selectedNode.label}</span>
                  <span className="text-[10px] text-slate-500 font-mono">[{selectedNode.kind}]</span>
                </div>
                <div className="text-[10px] text-slate-400 font-mono">
                  State: <span className="text-cyan-300">{selectedNode.state}</span> • Risk: <span className="text-amber-400">{selectedNode.riskTier}</span> • Trust: Tier {selectedNode.trustTier}
                </div>
              </div>
            )}

            <div className="absolute bottom-3 right-3 text-[10px] text-slate-500 bg-black/80 px-2 py-1 rounded border border-slate-800">
              Click node to inspect verification path • Halos indicate active policy/runtime transitions
            </div>
          </div>

          {/* Semantic DOM Fallback & Accessibility Mirror */}
          <div className="p-4 rounded-2xl bg-[#070b14] border border-slate-800 space-y-2">
            <div className="flex items-center justify-between text-xs font-bold text-slate-400">
              <span>ACCESSIBILITY & HTMX DOM FALLBACK MIRROR</span>
              <span className="text-cyan-400 font-mono">hx-get="/console/fragments/graph/current"</span>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs font-mono">
                <thead>
                  <tr className="border-b border-slate-800 text-slate-500 text-[10px]">
                    <th className="pb-1.5">NODE ID</th>
                    <th className="pb-1.5">KIND</th>
                    <th className="pb-1.5">LABEL</th>
                    <th className="pb-1.5">STATE</th>
                    <th className="pb-1.5">RISK TIER</th>
                    <th className="pb-1.5">TRUST TIER</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800/60">
                  {INITIAL_NODES.map((n) => (
                    <tr 
                      key={n.id} 
                      onClick={() => setSelectedNode(n)}
                      className={`hover:bg-slate-900/60 cursor-pointer ${selectedNode?.id === n.id ? 'bg-cyan-950/40 text-cyan-200' : 'text-slate-300'}`}
                    >
                      <td className="py-1.5 font-bold text-cyan-300">{n.id}</td>
                      <td className="py-1.5 text-slate-400">{n.kind}</td>
                      <td className="py-1.5">{n.label}</td>
                      <td className="py-1.5">
                        <span className={`px-1.5 py-0.5 rounded text-[9px] font-bold ${
                          n.state === 'verified' ? 'bg-emerald-950 text-emerald-300' :
                          n.state === 'approval_required' ? 'bg-amber-950 text-amber-300' :
                          'bg-cyan-950 text-cyan-300'
                        }`}>
                          {n.state}
                        </span>
                      </td>
                      <td className="py-1.5 text-amber-400">{n.riskTier}</td>
                      <td className="py-1.5 text-slate-400">Tier {n.trustTier}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* ================= TAB 3: VERSIONED JSON CONTRACTS ================= */}
      {activeTab === 'contracts' && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
          <div className="lg:col-span-1 space-y-2">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider block">
              CANONICAL CONTRACT SCHEMAS
            </span>
            {CONTRACT_SCHEMAS.map((schema) => (
              <button
                key={schema.id}
                onClick={() => setSelectedSchema(schema)}
                className={`w-full text-left p-3 rounded-xl border transition-all cursor-pointer ${
                  selectedSchema.id === schema.id
                    ? 'bg-[#120826] border-[#D4AF37] text-white shadow-[0_0_15px_rgba(212,175,55,0.2)]'
                    : 'bg-[#090d18] border-slate-800 text-slate-400 hover:text-slate-200'
                }`}
              >
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-cyan-300">{schema.name}</span>
                  <span className="text-[9px] px-1.5 py-0.2 rounded bg-black border border-slate-700 text-slate-400">
                    Epoch {schema.epoch}
                  </span>
                </div>
                <div className="text-[10px] text-[#D4AF37] mt-1 font-bold">
                  {schema.authority}
                </div>
                <p className="text-[11px] text-slate-400 mt-1 line-clamp-2">
                  {schema.description}
                </p>
              </button>
            ))}
          </div>

          <div className="lg:col-span-2 space-y-2">
            <div className="p-4 rounded-2xl bg-[#050505] border border-cyan-800/60 shadow-2xl space-y-2">
              <div className="flex items-center justify-between border-b border-slate-800 pb-2">
                <div>
                  <span className="text-xs font-bold text-[#D4AF37]">{selectedSchema.path}</span>
                  <div className="text-[10px] text-slate-400">Authority: {selectedSchema.authority} • Epoch: {selectedSchema.epoch}</div>
                </div>
                <button
                  onClick={() => {
                    navigator.clipboard.writeText(selectedSchema.sampleJson);
                  }}
                  className="px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-xs text-slate-300 transition-all cursor-pointer"
                >
                  Copy JSON
                </button>
              </div>

              <pre className="text-[11px] font-mono text-emerald-300 bg-black/90 p-3 rounded-xl overflow-x-auto max-h-96 leading-relaxed border border-slate-900">
                {selectedSchema.sampleJson}
              </pre>
            </div>
          </div>
        </div>
      )}

      {/* ================= TAB 4: GO / RUST AUTHORITY MATRIX ================= */}
      {activeTab === 'architecture' && (
        <div className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs font-mono">
            
            {/* Go Responsibilities */}
            <div className="p-4 rounded-2xl bg-[#070b14] border-2 border-sky-500/50 space-y-3 shadow-xl">
              <div className="flex items-center justify-between border-b border-sky-500/30 pb-2">
                <div className="flex items-center gap-2">
                  <span className="text-lg">🐹</span>
                  <h3 className="font-bold text-sky-300 text-sm">GO CONTROL PLANE (BIFROST / OPERATOR)</h3>
                </div>
                <span className="text-[10px] px-2 py-0.5 rounded bg-sky-950 text-sky-300 font-bold border border-sky-500/40">
                  NETWORK & INGRESS
                </span>
              </div>

              <ul className="space-y-2 text-slate-300">
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-sky-400 shrink-0 mt-0.5" />
                  <span><strong>mTLS Termination & Session Auth</strong>: Validates client sessions and derives TenantContext server-side.</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-sky-400 shrink-0 mt-0.5" />
                  <span><strong>HTMX Operator Console</strong>: Server-renders HTML fragments for missions, receipts, and approval requests.</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-sky-400 shrink-0 mt-0.5" />
                  <span><strong>World Tree Typed Retrieval Facade</strong>: Scoped REST/SSE APIs; never accepts client tenant_id.</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-sky-400 shrink-0 mt-0.5" />
                  <span><strong>Voice & Media Router</strong>: Webhook mediation with approved manifest lookup.</span>
                </li>
              </ul>

              <div className="p-2.5 rounded-xl bg-red-950/60 border border-red-500/50 text-[11px] text-red-200">
                <strong>MUST NOT DO</strong>: Bifrost must NEVER issue capability leases, authorize state mutations, or execute raw Cypher/Qdrant queries.
              </div>
            </div>

            {/* Rust Responsibilities */}
            <div className="p-4 rounded-2xl bg-[#070b14] border-2 border-amber-500/50 space-y-3 shadow-xl">
              <div className="flex items-center justify-between border-b border-amber-500/30 pb-2">
                <div className="flex items-center gap-2">
                  <span className="text-lg">🦀</span>
                  <h3 className="font-bold text-amber-300 text-sm">RUST PRIVILEGED WORKSPACE & VERIFIER</h3>
                </div>
                <span className="text-[10px] px-2 py-0.5 rounded bg-amber-950 text-amber-300 font-bold border border-amber-500/40">
                  PRIVILEGE & ISOLATION
                </span>
              </div>

              <ul className="space-y-2 text-slate-300">
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
                  <span><strong>Sentinel Lease Authority</strong>: Ed25519 signer/verifier for capability leases with monotonic authority epochs.</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
                  <span><strong>Gideon Verifier & Z3 Prover</strong>: Formal evidence verification against 44 safety theorems before effect execution.</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
                  <span><strong>VFS Guardian & Runtime Isolation</strong>: Path normalization, Wasmtime sandboxes, and cgroup v2 7.2GB hard throttling.</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
                  <span><strong>Receipt Journal</strong>: SQLite WAL2 append-only hash-chained journal for audit proof.</span>
                </li>
              </ul>

              <div className="p-2.5 rounded-xl bg-emerald-950/60 border border-emerald-500/50 text-[11px] text-emerald-200">
                <strong>CRITICAL RULE</strong>: Sentinel is the sole lease authority; VFS controls workspaces; Gideon only passes or blocks based on proved evidence.
              </div>
            </div>

          </div>

          {/* Canonical Directory Mapping */}
          <div className="p-4 rounded-2xl bg-black border border-slate-800 text-xs font-mono space-y-2">
            <span className="font-bold text-[#D4AF37] uppercase">CANONICAL CAMELOT-VPS REPOSITORY TOPOLOGY</span>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-2 text-slate-400 text-[11px]">
              <div className="p-2 rounded bg-slate-950 border border-slate-800">
                <span className="text-cyan-300 font-bold block">apps/</span>
                bifrost-hub (Go)<br />
                operator-console (Go HTMX)<br />
                lease-authority (Rust)<br />
                gideon (Rust Z3)<br />
                receipt-service (Rust)
              </div>
              <div className="p-2 rounded bg-slate-950 border border-slate-800">
                <span className="text-cyan-300 font-bold block">crates/</span>
                camelot-contracts<br />
                camelot-crypto<br />
                camelot-policy<br />
                camelot-lease<br />
                camelot-vfs / camelot-runtime
              </div>
              <div className="p-2 rounded bg-slate-950 border border-slate-800">
                <span className="text-cyan-300 font-bold block">internal-go/</span>
                auth / tenancy<br />
                bifrost / command<br />
                htmx / sse<br />
                clients (neo4j, qdrant)
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ================= TAB 5: ADVERSARIAL TEST SUITE ================= */}
      {activeTab === 'adversarial' && (
        <div className="space-y-4">
          <div className="p-4 rounded-2xl bg-[#090d18] border border-red-500/40 space-y-3">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-sm font-bold text-red-300 flex items-center gap-2">
                  <ShieldCheck className="w-4 h-4 text-red-400" />
                  <span>ADVERSARIAL ATTACK SIMULATION GAUNTLET</span>
                </h3>
                <p className="text-xs text-slate-400 mt-0.5">
                  Proves that the system fails closed against malicious client inputs, forged leases, and cross-tenant leakage.
                </p>
              </div>
              <span className="text-xs font-mono font-bold text-emerald-400">
                8/8 TESTS PASSING
              </span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-2">
              <button
                onClick={() => runAdversarialTest('Cross-tenant graph query', 'Bifrost enforces server-derived TenantContext; client tenant_id ignored')}
                className="p-2.5 rounded-xl bg-black hover:bg-slate-900 border border-slate-800 text-left text-xs font-mono space-y-1 transition-all cursor-pointer"
              >
                <div className="font-bold text-amber-300">1. Cross-Tenant Query</div>
                <div className="text-[10px] text-slate-500">Inject rogue tenant_id in request body</div>
              </button>

              <button
                onClick={() => runAdversarialTest('Forged Capability Lease', 'Rust lease authority verifies Ed25519 signature; rejects untrusted signer')}
                className="p-2.5 rounded-xl bg-black hover:bg-slate-900 border border-slate-800 text-left text-xs font-mono space-y-1 transition-all cursor-pointer"
              >
                <div className="font-bold text-amber-300">2. Forged Lease Token</div>
                <div className="text-[10px] text-slate-500">Client-synthesized Ed25519 payload</div>
              </button>

              <button
                onClick={() => runAdversarialTest('Stale Authority Epoch', 'Sentinel detects epoch mismatch; revocations immediately cascade')}
                className="p-2.5 rounded-xl bg-black hover:bg-slate-900 border border-slate-800 text-left text-xs font-mono space-y-1 transition-all cursor-pointer"
              >
                <div className="font-bold text-amber-300">3. Stale Epoch Replay</div>
                <div className="text-[10px] text-slate-500">Epoch 103 lease presented in Epoch 104</div>
              </button>

              <button
                onClick={() => runAdversarialTest('VFS Path Traversal', 'Rust vfs-guardian normalizes path; blocks ../ traversal out of workspace')}
                className="p-2.5 rounded-xl bg-black hover:bg-slate-900 border border-slate-800 text-left text-xs font-mono space-y-1 transition-all cursor-pointer"
              >
                <div className="font-bold text-amber-300">4. VFS Path Traversal</div>
                <div className="text-[10px] text-slate-500">Write to /etc/shadow or host root</div>
              </button>

              <button
                onClick={() => runAdversarialTest('Raw Cypher Injection', 'World Tree API facade denies raw queries; accepts only typed queries')}
                className="p-2.5 rounded-xl bg-black hover:bg-slate-900 border border-slate-800 text-left text-xs font-mono space-y-1 transition-all cursor-pointer"
              >
                <div className="font-bold text-amber-300">5. Raw Cypher Bypass</div>
                <div className="text-[10px] text-slate-500">MATCH (n) DETACH DELETE n</div>
              </button>

              <button
                onClick={() => runAdversarialTest('Qdrant Filter Omission', 'Rust/Go adapter mandates tenant_id filter before vector search')}
                className="p-2.5 rounded-xl bg-black hover:bg-slate-900 border border-slate-800 text-left text-xs font-mono space-y-1 transition-all cursor-pointer"
              >
                <div className="font-bold text-amber-300">6. Unfiltered Qdrant</div>
                <div className="text-[10px] text-slate-500">Vector search across foreign tenants</div>
              </button>

              <button
                onClick={() => runAdversarialTest('Stale Approval Window', 'Effect manifest rejects expired approval lease window')}
                className="p-2.5 rounded-xl bg-black hover:bg-slate-900 border border-slate-800 text-left text-xs font-mono space-y-1 transition-all cursor-pointer"
              >
                <div className="font-bold text-amber-300">7. Expired Approval</div>
                <div className="text-[10px] text-slate-500">Execute effect after 5m window</div>
              </button>

              <button
                onClick={() => runAdversarialTest('Receipt Chain Tampering', 'SQLite WAL2 hash validation fails; integrity alert broadcast via SSE')}
                className="p-2.5 rounded-xl bg-black hover:bg-slate-900 border border-slate-800 text-left text-xs font-mono space-y-1 transition-all cursor-pointer"
              >
                <div className="font-bold text-amber-300">8. Receipt Hash Tamper</div>
                <div className="text-[10px] text-slate-500">Mutate block #849 previous_hash</div>
              </button>
            </div>
          </div>

          {/* Adversarial Logs Console */}
          <div className="p-4 rounded-2xl bg-black border border-slate-800 space-y-2">
            <span className="text-xs font-bold text-slate-400 uppercase">TEST EXECUTION TELEMETRY LOG</span>
            <div className="space-y-1 font-mono text-xs max-h-48 overflow-y-auto">
              {adversarialLogs.map((log, i) => (
                <div key={i} className={log.includes('BLOCKED') ? 'text-emerald-400' : 'text-slate-300'}>
                  {log}
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

    </div>
  );
};
