[package]
name = "state-service"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
async-stream = "0.3"
camelot-crypto = { path = "../../crates/camelot-crypto" }
chrono = { version = "0.4.34", features = ["serde"] }
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite"] }
subtle = "2.6"
tokio = { version = "1.36", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1.7", features = ["v4", "serde"] }
